### ISSUE TITLE
セッションデータの読み込み時、セッションの開始or終了時間がxx:05だとチェックに引っかかる

### ISSUE THREAD

**Issue by chiemi627** [tsukuba-pbl/16-4_PosTom#73]
Scheduleメニューでセッションデータをcsvファイルから読み込ませるとき、
時間がxx:05だとエラーが表示されて読み込めない。

**Comment by chiemi627** [comment]
多分
https://github.com/tsukuba-pbl/16-4_PosTom/blob/master/app/Controller/SchedulesController.php#L187
で引っかかってるんだけど、なんでこんな条件があるのかよくわからん。

**Comment by ferretdayo** [comment]
phpの比較怖いなぁ...
=== と ==は違うので意図して使ってるのか....

**Comment by ferretdayo** [comment]
15分単位でしかできないとかあるのかな

**Comment by chiemi627** [comment]
実際には15分単位にする必要はないよ

**Comment by ferretdayo** [comment]
先生の言っている条件確かに意味が不明ですね．

splitしていた後の変数$timeStrを　$timeStr  != "0"もなんだかなぁ・・・

**Comment by ferretdayo** [comment]
IDCFクラウド２つのサーバとも反映させました。
closeします。
